// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace bytebaseDatabase.bytebase.Outputs
{

    [OutputType]
    public sealed class bytebaseSpec
    {
        /// <summary>
        /// Configuration needed to deploy a pod index.
        /// </summary>
        public readonly Outputs.bytebasePodSpec? Pod;
        /// <summary>
        /// Configuration needed to deploy a serverless index.
        /// </summary>
        public readonly Outputs.bytebaseServerlessSpec? Serverless;

        [OutputConstructor]
        private bytebaseSpec(
            Outputs.bytebasePodSpec? pod,

            Outputs.bytebaseServerlessSpec? serverless)
        {
            Pod = pod;
            Serverless = serverless;
        }
    }
}
