# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from . import _utilities
import typing
# Export this package's modules as members:
from .provider import *

# Make subpackages available:
if typing.TYPE_CHECKING:
    import pulumi_bytebase.bytebase as __bytebase
    bytebase = __bytebase
else:
    bytebase = _utilities.lazy_import('pulumi_bytebase.bytebase')

_utilities.register(
    resource_modules="""
[
 {
  "pkg": "bytebase",
  "mod": "bytebase",
  "fqn": "pulumi_bytebase.bytebase",
  "classes": {
   "bytebase:bytebase:Random": "Random"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "bytebase",
  "token": "pulumi:providers:bytebase",
  "fqn": "pulumi_bytebase",
  "class": "Provider"
 }
]
"""
)
