# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from . import _utilities
import typing
# Export this package's modules as members:
from ._enums import *
from .lookup_bytebase_collection import *
from .lookup_bytebase_index import *
from .bytebase_collection import *
from .bytebase_index import *
from .provider import *
from ._inputs import *
from . import outputs

# Make subpackages available:
if typing.TYPE_CHECKING:
    import bytebase_pulumi.config as __config
    config = __config
else:
    config = _utilities.lazy_import('bytebase_pulumi.config')

_utilities.register(
    resource_modules="""
[
 {
  "pkg": "bytebase",
  "mod": "index",
  "fqn": "bytebase_pulumi",
  "classes": {
   "bytebase:index:bytebaseCollection": "bytebaseCollection",
   "bytebase:index:bytebaseIndex": "bytebaseIndex"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "bytebase",
  "token": "pulumi:providers:bytebase",
  "fqn": "bytebase_pulumi",
  "class": "Provider"
 }
]
"""
)
